swagger: "2.0"
info:
  description: This is an API to search for employees by a certain criteria and return those that match it.
  version: 1.0.0
  title: WorkForce API
  contact:
    email: tainabatistaconde@gmail.com
    
host: http://localhost:3001
basePath: /

paths:
  /employees:
    get:
      summary: get all employees.
      produces:
        - application/json
      responses:
        200:
          description: a list of employees
          schema:
            type: array
            items:
              $ref: "#/definitions/EmployeeItem"
        500:
          description: There was an error
    post:
      summary: creates a new employee 
      security: 
        - ApiKeyAuth: []
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: newEmployee
          description: New employee to add
          schema:
            $ref: "#/definitions/EmployeeItem"
      responses:
        200:
          description: employee added
        500:
          description: There was an error.
  /employees/{cpf} :
    get:
      summary: get an employee by cpf
      parameters:
        - in: path
        name: cpf
        required: true
        type: string
        minimun: 11 characters
        description: CPF is a unique id for each employee. It is similar to a Social Security Number in the US. 
      procudes: 
        - application/json
      responses:
        200:
          description: An Employee object was created
          schema:
            $ref: "#/definitions/EmployeeItem"
        500:
          description: There was an error.
    put:
      summary: update an existing employee in the system.
      security: 
        - ApiKeyAuth: []
      parameters:
        - in: path
        name: cpf
        required: true
        type: string
        minimun: 11 characters
        description: CPF is a unique id for each employee. It is similar to a Social Security Number in the US.
        - in: body
        name: editedEmployee
        description: Employee object that needs to be updated
        required: true
        schema: 
          $ref: "#/definitions/EmployeeItem"
      consumes:
        - application/json
      produces:
        - application/json
      responses:
      200:
        description: An Employee object was updated
        schema:
          $ref: "#/definitions/EmployeeItem"
      500:
        description: There was an error.
    delete:
      summary: deletes an employee by CPF
      produces:
        - application/json
      parameters:
        - in : path
        name: cpf
        required: true
        type: string
        minimun: 11 characters
        description: CPF is a unique id for each employee. It is similar to a Social Security Number in the US.
      responses:
      200:
        description: An Employee object was deleted
        schema:
          $ref: "#/definitions/EmployeeItem"
      500:
        description: There was an error.
  /employees/{criterioBusca}/{query}:
    get: 
      summary: find an employee by search criteria
      produces:
        - application/json
      parameters:
        - in : path
        name : criterioBusca
        required: true
        type: string
        description: This is the search criteria, it can be nome, cargo, salario, status, ufNasc, dataCad, cpf.
        - in: path
        name: query
        required: true
        type: string
        description: The query is the term the user is looking for to match in the employee info related to the search criteria. 
      responses:
        200:
          description: A list of employees
          schema:
            type: array
            items:
              $ref: "#/definitions/EmployeeItem"
        500:
          description: There was an error.
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: app      
definitions:
  EmployeeItem:
    type: object
    required:
      - nome
      - cpf
      - dataCad
      - cargo
      - ufNasc
      - salario
      - status
      - deleted
    properties:
      nome:
        type: string
        example: Juscelino Kubitschek
      cpf:
        type: string
        example: "12345678901"
      dataCad:
        type: string
        format: dd/MM/yyyy
        example: 29/6/2021
      cargo: 
        type: string
        example: AC Sr
      ufNasc: 
        type: string
        example: DF
      status: 
        type: string
        example: ATIVO
      salario:
        type: float
        example: 5500.5
      deleted:
        type: boolean

