swagger: "2.0"
info:
  description: This is an API to search for employees by a certain criteria and return those that match it.
  version: 1.0.0
  title: WorkForce API
  contact:
    email: tainabatistaconde@gmail.com
host: http://localhost:3001
basePath: /

paths:
  /employees:
    get:
      summary: get all employees.
      produces:
        - application/json
      responses:
        200:
          description: a list of employees
          schema:
            type: array
            items:
              $ref: "#/definitions/EmployeeItem"
        500:
          description: There was an error
    post:
      summary: creates a new employee 
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: newEmployee
          description: New employee to add
          schema:
            $ref: "#/definitions/EmployeeItem"
      responses:
        200:
          description: employee added
        500:
          description: There was an error.
  /employees/{cpf} :
    get:
      summary: get an employee by cpf
      parameters:
        - in: path
        name: cpf
        required: true
        type: string
        minimun: 11
        description: CPF is a unique id for each employee. It is similar to a Social Security Number in the US. 
      procudes: 
        - application/json
      responses:
        200:
          description: An Employee object
          schema:
            $ref: "#/definitions/EmployeeItem"
        500:
          description: There was an error.
    put:
      summary: 
            
      
        
definitions:
  EmployeeItem:
    type: object
    required:
      - nome
      - cpf
      - dataCad
      - cargo
      - ufNasc
      - salario
      - status
      - deleted
    properties:
      nome:
        type: string
        example: Juscelino Kubitschek
      cpf:
        type: string
        example: "12345678901"
      dataCad:
        type: string
        format: dd/MM/yyyy
        example: 29/6/2021
      cargo: 
        type: string
        example: AC Sr
      ufNasc: 
        type: string
        example: DF
      status: 
        type: string
        example: ATIVO
      salario:
        type: float
        example: 5500.5
      deleted:
        type: boolean

  Manufacturer:
    required:
      - name
    properties:
      name:
        type: string
        example: ACME Corporation
      homePage:
        type: string
        format: url
        example: https://www.acme-corp.com
      phone:
        type: string
        example: 408-867-5309
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /Taina-conde/example/1.0.0
schemes:
  - https
